### ISSUE TITLE
Events list display

### ISSUE THREAD

**Issue by tizot** [tizot/jtx-client#1]
Maybe it could be nice to display the events in a grid instead of a list of div. For example, the grid view of the former (and not regretted) WordPress for articles was not so bad to display events (or projections, or videos, ...).
Note that a poster will bo add to event object. 
Another idea is the view of albums in iTunes (when you click on an album, the list of tracks appear with a smooth opening effect).

**Comment by denismerigoux** [comment]
Ouais la grille c'est prévu, l'affichage tel qu'il est maintenant c'est du provisoire.
