### ISSUE TITLE
Bootstrap not correctly handled by bower

### ISSUE THREAD

**Issue by tizot** [tizot/jtx-client#4]
There is a recurrent issue with bootstrap, whose CSS is not inserted in gulp build. I propose that this CSS be inserted directly in index.html, and the .css file (and the fonts) be placed in assets/ directory. 
Moreover, I think we could select only some components of Boostrap (http://getbootstrap.com/customize).

**Comment by denismerigoux** [comment]
Bootstrap files now in the assets/ directory.
